name: covid-19-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas=0.25.0
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - numpy=1.16.0
  - scikit-learn=0.20.3
  - statsmodels=0.9.0
  - voila=0.2.3
  - plotly=4.1
  - jupyter=1.0.0
  - jupyterlab=3.0.1
  - pip=20.0
